; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; MegaST: Remember the mounted disk images and the manually loaded CRTs/ROMs
;
; The full path of every mounted disk image (one entry per virtual drive) and
; of every manually loaded CRT/ROM (one entry per CRT/ROM, behind the vdrive
; entries) is kept in MNT_PATHS and saved to the file MNT_FILE (config.vhd,
; selector M2M$CFG_MNT_FILE). At the next start of the core, MNT_RESTORE
; loads them again while the core is still held in reset, so that for example
; a hard disk or a TOS ROM is in place before the machine boots.
;
; Like the settings file (CFG_FILE), the file needs to exist with the exact
; size of MNT_BUF_SIZE bytes (MNT_ENTRIES entries of MNT_ENTRY_SZ bytes, see
; globals.asm generated by make_rom.sh), otherwise the feature is off. Each
; entry is a zero-terminated path; an entry that starts with 0x00 or 0xFF is
; empty, so a file filled with either value is a valid "nothing mounted" file.
;
; The file is accessed through HANDLE_DEV, the same device handle that the
; vdrives use, so that the FAT32 library keeps the shared 512-byte sector
; buffer consistent (see the comment about CONFIG_DEVH in shell_vars.asm).
;
; The file browser (selectfile.asm) tracks its current directory in FB_PATH
; (FBP_SET, FBP_CD), because it only returns the bare file name.
;
; done by Chris Freeman in 2026 and licensed under GPL v3
; ****************************************************************************

; ----------------------------------------------------------------------------
; File browser path tracking
; ----------------------------------------------------------------------------

; Set FB_PATH to the given absolute path
; Input:  R8: zero-terminated path
; Output: none, all registers unchanged
FBP_SET         SYSCALL(enter, 1)

                MOVE    FB_PATH, R0
                SYSCALL(strlen, 1)              ; R9: length
                CMP     R9, FB_PATH_MAX         ; too long?
                RBRA    _FBPS_INV, N            ; yes: path unknown
                MOVE    R0, R9
                SYSCALL(strcpy, 1)
                RBRA    _FBPS_RET, 1

_FBPS_INV       MOVE    0, @R0                  ; empty FB_PATH = unknown

_FBPS_RET       SYSCALL(leave, 1)
                RET

; Apply a directory change of the file browser to FB_PATH
; Input:  R8: directory name relative to FB_PATH, ".." means one level up
; Output: none, all registers unchanged
FBP_CD          SYSCALL(enter, 1)

                MOVE    R8, R2                  ; R2: directory name
                MOVE    FB_PATH, R0
                CMP     0, @R0                  ; path unknown?
                RBRA    _FBPC_RET, Z            ; yes: stays unknown

                MOVE    FN_UPDIR, R9            ; ".."?
                SYSCALL(strcmp, 1)
                CMP     0, R10
                RBRA    _FBPC_DOWN, !Z          ; no

                ; one level up: cut FB_PATH at its last '/'
                MOVE    R0, R1                  ; R1: running pointer
                MOVE    R0, R3                  ; R3: position of last '/'
_FBPC_UP1       CMP     0, @R1                  ; end of string?
                RBRA    _FBPC_UP2, Z
                CMP     0x002F, @R1             ; '/'?
                RBRA    _FBPC_UP1N, !Z
                MOVE    R1, R3
_FBPC_UP1N      ADD     1, R1
                RBRA    _FBPC_UP1, 1
_FBPC_UP2       CMP     R0, R3                  ; last '/' is the root?
                RBRA    _FBPC_UP3, !Z           ; no
                ADD     1, R3                   ; yes: keep the "/"
_FBPC_UP3       MOVE    0, @R3
                RBRA    _FBPC_RET, 1

_FBPC_DOWN      MOVE    R2, R8                  ; "."?
                MOVE    FBP_DOT, R9
                SYSCALL(strcmp, 1)
                CMP     0, R10
                RBRA    _FBPC_RET, Z            ; yes: nothing changes

                MOVE    R0, R8                  ; append "/" (if needed)..
                MOVE    R2, R9                  ; ..and the directory name
                RSUB    _MNT_JOIN, 1
                CMP     0, R8                   ; too long?
                RBRA    _FBPC_RET, !Z           ; no
                MOVE    0, @R0                  ; yes: path unknown

_FBPC_RET       SYSCALL(leave, 1)
                RET

; Append "/" (unless the path ends with it) and a name to a path
; Input:  R8: path (buffer with room for FB_PATH_MAX + 1 words)
;         R9: name
; Output: R8: 0 if the result would be longer than FB_PATH_MAX (the path is
;             unchanged then), otherwise unchanged
;         R9: changed
_MNT_JOIN       INCRB

                MOVE    R8, R0                  ; R0: path
                MOVE    R9, R1                  ; R1: name
                SYSCALL(strlen, 1)              ; R9: length of the path
                MOVE    R9, R2                  ; R2: length of the result
                MOVE    R0, R3
                ADD     R9, R3                  ; R3: end of the path
                XOR     R4, R4                  ; R4: 1 if "/" needed
                CMP     0, R9
                RBRA    _MNTJ_1, Z
                CMP     0x002F, @--R3           ; ends with '/'?
                RBRA    _MNTJ_0, Z
                MOVE    1, R4
_MNTJ_0         ADD     1, R3                   ; R3: end of the path again
_MNTJ_1         ADD     R4, R2
                MOVE    R1, R8
                SYSCALL(strlen, 1)
                ADD     R9, R2                  ; R2: length of the result
                CMP     R2, FB_PATH_MAX         ; too long?
                RBRA    _MNTJ_ERR, N            ; yes

                CMP     0, R4
                RBRA    _MNTJ_2, Z
                MOVE    0x002F, @R3++           ; add '/'
_MNTJ_2         MOVE    R1, R8
                MOVE    R3, R9
                SYSCALL(strcpy, 1)
                MOVE    R0, R8
                RBRA    _MNTJ_RET, 1

_MNTJ_ERR       XOR     R8, R8

_MNTJ_RET       DECRB
                RET

; ----------------------------------------------------------------------------
; Bookkeeping: called by HANDLE_MOUNTING (shell.asm)
; ----------------------------------------------------------------------------

; Remember the image that has just been mounted or loaded
; Input:  R8: vdrive or CRT/ROM id
;         R9: mode: 0=vdrive, 1=CRT/ROM
;        R10: file name (inside the directory FB_PATH)
; Output: none, all registers unchanged
MNT_REMEMBER    SYSCALL(enter, 1)

                MOVE    MNT_ON, R0
                CMP     0, @R0
                RBRA    _MNTR_RET, Z

                MOVE    R10, R2                 ; R2: file name
                RSUB    _MNT_ENTRY, 1           ; R8: entry
                MOVE    R8, R0                  ; R0: entry
                MOVE    0, @R0                  ; empty entry, in case..
                MOVE    FB_PATH, R8             ; ..the path is unknown or..
                CMP     0, @R8                  ; ..too long
                RBRA    _MNTR_DIRTY, Z
                MOVE    R0, R9
                SYSCALL(strcpy, 1)
                MOVE    R0, R8
                MOVE    R2, R9
                RSUB    _MNT_JOIN, 1
                CMP     0, R8                   ; too long?
                RBRA    _MNTR_DIRTY, !Z         ; no
                MOVE    0, @R0                  ; yes: forget it

_MNTR_DIRTY     MOVE    MNT_DIRTY, R0
                MOVE    1, @R0

_MNTR_RET       SYSCALL(leave, 1)
                RET

; Forget the image of a drive that has been unmounted
; Input:  R8: vdrive or CRT/ROM id
;         R9: mode: 0=vdrive, 1=CRT/ROM
; Output: none, all registers unchanged
MNT_FORGET      SYSCALL(enter, 1)

                MOVE    MNT_ON, R0
                CMP     0, @R0
                RBRA    _MNTF_RET, Z

                RSUB    _MNT_ENTRY, 1
                MOVE    0, @R8
                MOVE    MNT_DIRTY, R0
                MOVE    1, @R0

_MNTF_RET       SYSCALL(leave, 1)
                RET

; Return the entry in MNT_PATHS for a vdrive or a CRT/ROM
; Input:  R8: vdrive or CRT/ROM id
;         R9: mode: 0=vdrive, 1=CRT/ROM
; Output: R8: pointer to the entry
_MNT_ENTRY      INCRB

                CMP     0, R9                   ; CRT/ROM?
                RBRA    _MNTE_1, Z              ; no
                ADD     VDRIVES_MAX, R8         ; yes: behind the vdrives
_MNTE_1         MOVE    R8, R0                  ; R0: entry number
                MOVE    MNT_ENTRY_SZ, R1
                MOVE    MNT_PATHS, R8
_MNTE_2         CMP     0, R0                   ; entry number * size
                RBRA    _MNTE_RET, Z
                ADD     R1, R8
                SUB     1, R0
                RBRA    _MNTE_2, 1

_MNTE_RET       DECRB
                RET

; ----------------------------------------------------------------------------
; Save MNT_PATHS to MNT_FILE, if there are changes
;
; Called after mounting (HANDLE_MOUNTING) and when the menu closes
; (HELP_MENU), so that a save that had to be postponed is retried.
; ----------------------------------------------------------------------------

MNT_SAVE        SYSCALL(enter, 1)

                MOVE    MNT_ON, R0
                CMP     0, @R0
                RBRA    _MNTS_RET, Z
                MOVE    MNT_DIRTY, R0
                CMP     0, @R0
                RBRA    _MNTS_RET, Z
                MOVE    HANDLE_DEV, R0          ; SD card not mounted (it is
                CMP     0, @R0                  ; re-mounted after a card
                RBRA    _MNTS_RET, Z            ; change): try again later

                ; The file stays on the SD card that was active at startup
                ; (like the settings, see ROSM_INTEGRITY)
                MOVE    M2M$CSR, R8
                MOVE    @R8, R8
                AND     M2M$CSR_SD_ACTIVE, R8
                MOVE    INITIAL_SD, R9
                CMP     R8, @R9
                RBRA    _MNTS_1, Z
                MOVE    LOG_MNT_SDC, R8
                RBRA    _MNTS_OFF, 1

                ; Postpone while the write cache of a vdrive is dirty, like
                ; ROSM_SAVE does (options.asm)
_MNTS_1         RSUB    VD_ACTIVE, 1
                RBRA    _MNTS_3, !C
                MOVE    R8, R0                  ; R0: amount of vdrives
                XOR     R1, R1                  ; R1: vdrive id
_MNTS_2         MOVE    R1, R8
                MOVE    VD_CACHE_DIRTY, R9
                RSUB    VD_DRV_READ, 1
                CMP     0, R8                   ; dirty?
                RBRA    _MNTS_RET, !Z           ; yes: try again later
                ADD     1, R1
                CMP     R0, R1
                RBRA    _MNTS_2, !Z

_MNTS_3         MOVE    HANDLE_DEV, R8          ; open the file
                MOVE    MNT_FDH, R9
                MOVE    MNT_FNAME, R10
                XOR     R11, R11
                SYSCALL(f32_fopen, 1)
                CMP     0, R10
                RBRA    _MNTS_4, Z
                MOVE    LOG_MNT_EOPEN, R8
                RBRA    _MNTS_OFF, 1

_MNTS_4         MOVE    R9, R8                  ; R8: file handle
                MOVE    MNT_PATHS, R0           ; R0: data
                MOVE    MNT_BUF_SIZE, R1        ; R1: bytes to write
_MNTS_5         MOVE    @R0++, R9
                AND     0x00FF, R9
                SYSCALL(f32_fwrite, 1)
                CMP     0, R9
                RBRA    _MNTS_EWR, !Z
                SUB     1, R1
                RBRA    _MNTS_5, !Z
                SYSCALL(f32_fflush, 1)
                CMP     0, R9
                RBRA    _MNTS_EWR, !Z

                MOVE    MNT_DIRTY, R0
                MOVE    0, @R0
                MOVE    LOG_MNT_SAVED, R8
                SYSCALL(puts, 1)
                RBRA    _MNTS_RET, 1

_MNTS_EWR       MOVE    LOG_MNT_EWRITE, R8

                ; log the reason and stop remembering for this session
_MNTS_OFF       SYSCALL(puts, 1)
                MOVE    MNT_ON, R0
                MOVE    0, @R0

_MNTS_RET       SYSCALL(leave, 1)
                RET

; ----------------------------------------------------------------------------
; Restore the remembered images at startup
;
; Called by START_SHELL after CRTROM_AUTOLOAD and before RP_SYSTEM_START,
; i.e. while the core is still held in reset.
; ----------------------------------------------------------------------------

MNT_RESTORE     SYSCALL(enter, 1)

                MOVE    MNT_ON, R0
                MOVE    0, @R0
                MOVE    MNT_DIRTY, R0
                MOVE    0, @R0
                MOVE    MNT_SHOWN, R0
                MOVE    0, @R0
                MOVE    MNT_PEND, R8            ; no file names pending
                MOVE    MNT_ENTRIES, R9
                XOR     R10, R10
                SYSCALL(memset, 1)
                MOVE    MNT_PATHS, R8           ; all entries empty
                MOVE    MNT_BUF_SIZE, R9
                SYSCALL(memset, 1)

                ; file name from config.vhd: empty means feature off
                MOVE    M2M$RAMROM_DEV, R0
                MOVE    M2M$CONFIG, @R0
                MOVE    M2M$RAMROM_4KWIN, R0
                MOVE    M2M$CFG_MNT_FILE, @R0
                MOVE    M2M$RAMROM_DATA, R8
                CMP     0, @R8
                RBRA    _MNTRS_RET, Z
                SYSCALL(strlen, 1)
                CMP     R9, MNT_FNAME_MAX
                RBRA    _MNTRS_RET, N
                MOVE    MNT_FNAME, R9
                SYSCALL(strcpy, 1)

                MOVE    LOG_MNT_FILE, R8
                SYSCALL(puts, 1)
                MOVE    MNT_FNAME, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; mount the SD card for HANDLE_DEV (HANDLE_MOUNTING then
                ; skips this step)
                MOVE    HANDLE_DEV, R8
                CMP     0, @R8
                RBRA    _MNTRS_1, !Z
                RSUB    WAIT_FOR_SD, 1
                MOVE    1, R9                   ; partition #1 hardcoded
                SYSCALL(f32_mnt_sd, 1)
                CMP     0, R9
                RBRA    _MNTRS_1, Z
                MOVE    0, @R8                  ; not mounted
                MOVE    LOG_MNT_ESD, R8
                RBRA    _MNTRS_LOG, 1

                ; open the file and check its size
_MNTRS_1        MOVE    MNT_FDH, R9
                MOVE    MNT_FNAME, R10
                XOR     R11, R11
                SYSCALL(f32_fopen, 1)
                CMP     0, R10
                RBRA    _MNTRS_2, Z
                MOVE    LOG_MNT_ENOF, R8
                RBRA    _MNTRS_LOG, 1

_MNTRS_2        MOVE    R9, R8                  ; R8: file handle
                MOVE    R9, R0
                ADD     FAT32$FDH_SIZE_HI, R0
                CMP     0, @R0
                RBRA    _MNTRS_ESZ, !Z
                MOVE    R9, R0
                ADD     FAT32$FDH_SIZE_LO, R0
                CMP     MNT_BUF_SIZE, @R0
                RBRA    _MNTRS_3, Z
_MNTRS_ESZ      MOVE    LOG_MNT_ESIZE, R8
                RBRA    _MNTRS_LOG, 1

                ; read the entries
_MNTRS_3        MOVE    MNT_PATHS, R0           ; R0: data
                MOVE    MNT_BUF_SIZE, R1        ; R1: bytes to read
_MNTRS_4        SYSCALL(f32_fread, 1)
                CMP     0, R10
                RBRA    _MNTRS_5, Z
                MOVE    LOG_MNT_EREAD, R8
                RBRA    _MNTRS_LOG, 1
_MNTRS_5        CMP     0x00FF, R9              ; 0xFF counts as end of string
                RBRA    _MNTRS_6, !Z
                XOR     R9, R9
_MNTRS_6        MOVE    R9, @R0++
                SUB     1, R1
                RBRA    _MNTRS_4, !Z

                ; make sure that every entry is terminated
                MOVE    MNT_PATHS, R0
                ADD     MNT_ENTRY_SZ, R0
                SUB     1, R0
                MOVE    MNT_ENTRIES, R1
_MNTRS_7        MOVE    0, @R0
                ADD     MNT_ENTRY_SZ, R0
                SUB     1, R1
                RBRA    _MNTRS_7, !Z

                MOVE    MNT_ON, R0
                MOVE    1, @R0

                ; CRTs/ROMs first: some CRT/ROM loads unmount drives
                XOR     R1, R1                  ; R1: CRT/ROM id
                MOVE    CRTROM_MAN_NUM, R2
                MOVE    @R2, R2                 ; R2: amount of CRTs/ROMs
_MNTRS_8        CMP     R2, R1
                RBRA    _MNTRS_9, Z
                MOVE    R1, R8
                MOVE    1, R9
                RSUB    _MNT_LOAD, 1
                ADD     1, R1
                RBRA    _MNTRS_8, 1

_MNTRS_9        XOR     R1, R1                  ; R1: vdrive id
                MOVE    VDRIVES_NUM, R2
                MOVE    @R2, R2                 ; R2: amount of vdrives
_MNTRS_10       CMP     R2, R1
                RBRA    _MNTRS_11, Z
                MOVE    R1, R8
                XOR     R9, R9
                RSUB    _MNT_LOAD, 1
                ADD     1, R1
                RBRA    _MNTRS_10, 1

_MNTRS_11       MOVE    MNT_SHOWN, R0           ; hide the window, if shown
                CMP     0, @R0
                RBRA    _MNTRS_12, Z
                RSUB    SCR$OSM_OFF, 1
_MNTRS_12       RSUB    VD_MNT_ST_SET, 1        ; remember mount status
                RBRA    _MNTRS_RET, 1

_MNTRS_LOG      SYSCALL(puts, 1)

_MNTRS_RET      SYSCALL(leave, 1)
                RET

; Load one remembered image (part of MNT_RESTORE)
; Input:  R8: vdrive or CRT/ROM id
;         R9: mode: 0=vdrive, 1=CRT/ROM
; Output: none, all registers unchanged
_MNT_LOAD       SYSCALL(enter, 1)

                MOVE    R8, R7                  ; R7: id
                MOVE    R9, R5                  ; R5: mode
                RSUB    _MNT_ENTRY, 1
                MOVE    R8, R2                  ; R2: path
                CMP     0, @R2                  ; empty entry?
                RBRA    _MNTL_RET, Z            ; yes

                MOVE    LOG_MNT_LOAD, R8
                SYSCALL(puts, 1)
                MOVE    R2, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; LOAD_IMAGE goes fatal if the file cannot be opened, so check
                ; first (the card might be a different one or the file gone)
                MOVE    HANDLE_DEV, R8
                MOVE    MNT_FDH, R9
                MOVE    R2, R10
                XOR     R11, R11
                SYSCALL(f32_fopen, 1)
                CMP     0, R10
                RBRA    _MNTL_1, Z
                MOVE    LOG_MNT_ENOIMG, R8      ; keep the entry
                SYSCALL(puts, 1)
                RBRA    _MNTL_RET, 1

                ; LOAD_IMAGE draws its progress bar into the big window
_MNTL_1         MOVE    MNT_SHOWN, R0
                CMP     0, @R0
                RBRA    _MNTL_2, !Z
                MOVE    1, @R0
                RSUB    SCR$OSM_OFF, 1
                RSUB    FRAME_FULLSCR, 1
                RSUB    SCR$OSM_M_ON, 1
_MNTL_2         RSUB    SCR$CLRINNER, 1
                MOVE    1, R8
                MOVE    1, R9
                RSUB    SCR$GOTOXY, 1
                MOVE    STR_MNT_LOAD, R8
                RSUB    SCR$PRINTSTR, 1
                MOVE    R2, R8
                RSUB    _MNT_BASENAME, 1
                RSUB    SCR$PRINTSTR, 1

                MOVE    SF_CONTEXT, R0          ; context for PREP_LOAD_IMAGE
                MOVE    CTX_MOUNT_DISKIMG, @R0
                CMP     0, R5
                RBRA    _MNTL_3, Z
                MOVE    CTX_LOAD_ROM, @R0
_MNTL_3         MOVE    R7, R8
                MOVE    R2, R9
                MOVE    R5, R10
                RSUB    LOAD_IMAGE, 1
                MOVE    SF_CONTEXT, R0
                MOVE    0, @R0
                CMP     0, R8                   ; everything OK?
                RBRA    _MNTL_4, Z              ; yes

                MOVE    LOG_MNT_ELOAD, R8       ; no: the file is not usable,
                SYSCALL(puts, 1)                ; so forget it
                MOVE    R7, R8
                MOVE    R5, R9
                RSUB    MNT_FORGET, 1
                RBRA    _MNTL_RET, 1

                ; vdrives: notify the core (like HANDLE_MOUNTING)
_MNTL_4         MOVE    R9, R6                  ; R6: image type
                CMP     0, R5
                RBRA    _MNTL_5, !Z
                MOVE    R7, R8
                MOVE    HNDL_VD_FILES, R9
                ADD     R7, R9
                MOVE    @R9, R9
                MOVE    R9, R10
                ADD     FAT32$FDH_SIZE_LO, R9
                MOVE    @R9, R9                 ; R9: file size: low word
                ADD     FAT32$FDH_SIZE_HI, R10
                MOVE    @R10, R10               ; R10: file size: high word
                XOR     R11, R11                ; 0=read/write disk
                MOVE    R6, R12                 ; R12: disk image type
                RSUB    VD_STROBE_IM, 1
                MOVE    R7, R8                  ; menu index of the vdrive
                RSUB    VD_MENGRP, 1
                RBRA    _MNTL_6, 1
_MNTL_5         MOVE    R7, R8                  ; menu index of the CRT/ROM
                RSUB    CRTROM_M_GI, 1
_MNTL_6         RBRA    _MNTL_7, !C
                MOVE    R9, R8                  ; mark the menu item as..
                RSUB    _MNT_CFM_SET, 1         ; ..mounted/loaded

_MNTL_7         MOVE    R7, R8                  ; show the file name in the
                MOVE    R5, R9                  ; menu as soon as it opens
                RSUB    _MNT_ENTRY, 1
                SUB     MNT_PATHS, R8           ; entry number = offset / size
                XOR     R0, R0
_MNTL_8         CMP     0, R8
                RBRA    _MNTL_9, Z
                SUB     MNT_ENTRY_SZ, R8
                ADD     1, R0
                RBRA    _MNTL_8, 1
_MNTL_9         MOVE    MNT_PEND, R8
                ADD     R0, R8
                MOVE    1, @R8

_MNTL_RET       SYSCALL(leave, 1)
                RET

; Set the bit of a menu item in M2M$CFM_DATA
; Input:  R8: menu index
_MNT_CFM_SET    INCRB

                MOVE    R8, R0
                MOVE    R8, R1
                AND     0xFFFB, SR              ; clear Carry
                SHR     4, R0                   ; R0: window = index / 16
                AND     0x000F, R1              ; R1: bit = index % 16
                MOVE    M2M$CFM_ADDR, R2
                MOVE    R0, @R2
                MOVE    1, R3
                AND     0xFFFD, SR              ; clear X
                SHL     R1, R3
                MOVE    M2M$CFM_DATA, R2
                OR      R3, @R2

                DECRB
                RET

; Return the file name part of a path
; Input:  R8: path
; Output: R8: pointer behind the last '/' (or R8 if there is none)
_MNT_BASENAME   INCRB

                MOVE    R8, R0
_MNTB_1         CMP     0, @R0
                RBRA    _MNTB_RET, Z
                CMP     0x002F, @R0++
                RBRA    _MNTB_1, !Z
                MOVE    R0, R8
                RBRA    _MNTB_1, 1

_MNTB_RET       DECRB
                RET

; ----------------------------------------------------------------------------
; Menu support
; ----------------------------------------------------------------------------

; Write the file names of the restored images to OPTM_HEAP, where the menu
; shows them. OPTM_HEAP only becomes valid when the menu opens for the first
; time, so HELP_MENU calls this every time it opens the menu.
MNT_OSM_NAMES   SYSCALL(enter, 1)

                XOR     R1, R1                  ; R1: entry number
_MNTO_1         MOVE    MNT_PEND, R0
                ADD     R1, R0
                CMP     0, @R0                  ; name pending?
                RBRA    _MNTO_NEXT, Z
                MOVE    0, @R0

                MOVE    R1, R8                  ; R8: id, R9: mode
                XOR     R9, R9
                CMP     VDRIVES_MAX, R8
                RBRA    _MNTO_2, N
                SUB     VDRIVES_MAX, R8
                MOVE    1, R9
_MNTO_2         MOVE    R8, R2
                MOVE    R9, R3
                RSUB    _MNT_ENTRY, 1
                RSUB    _MNT_BASENAME, 1
                MOVE    R8, R10                 ; R10: file name
                MOVE    R2, R8
                MOVE    R3, R9
                RSUB    MNT_OSM_NAME, 1

_MNTO_NEXT      ADD     1, R1
                CMP     MNT_ENTRIES, R1
                RBRA    _MNTO_1, !Z

                SYSCALL(leave, 1)
                RET

; Store the file name of a vdrive or CRT/ROM where the menu shows it instead
; of "%s" (moved here from HANDLE_MOUNTING in shell.asm, so that MNT_RESTORE
; can use it, too)
;
; The convention for the position in the @OPTM_HEAP is:
; a) for vdrives: vdrive number times @SCR$OSM_O_DX
; b) for CRTs/ROMs: (#vdrives+#submenus+crt/rom id) times @SCR$OSM_O_DX
;
; Input:  R8: vdrive or CRT/ROM id
;         R9: mode: 0=vdrive, 1=CRT/ROM
;        R10: file name
; Output: none, all registers unchanged
MNT_OSM_NAME    SYSCALL(enter, 1)

                MOVE    R8, R7                  ; R7: id
                MOVE    R9, R5                  ; R5: mode
                MOVE    R10, R2                 ; R2: file name
                MOVE    OPTM_HEAP, R0
                MOVE    @R0, R0
                RBRA    _MNTN_1, !Z             ; OPTM_HEAP is ready
                MOVE    ERR_FATAL_INST, R8
                MOVE    ERR_FATAL_INST7, R9
                RBRA    FATAL, 1

_MNTN_1         XOR     R8, R8
                CMP     1, R5                   ; case (b)?
                RBRA    _MNTN_2, !Z             ; no, case (a)
                MOVE    VDRIVES_NUM, R9
                ADD     @R9, R8
                MOVE    OPTM_SCOUNT, R9
                ADD     @R9, R8

_MNTN_2         ADD     R7, R8
                MOVE    SCR$OSM_O_DX, R9
                MOVE    @R9, R9
                SYSCALL(mulu, 1)
                ADD     R10, R0                 ; R0: string ptr for file name
                MOVE    R9, R1                  ; R1: maximum string length
                SUB     2, R1                   ; minus 2 because of frame

                ; if the length of the name is <= the maximum size then just
                ; copy as is; otherwise copy maximum size + 1 so that the
                ; ellipsis is triggered (see _OPTM_CBS_REPL in options.asm)
                MOVE    R2, R8
                SYSCALL(strlen, 1)
                CMP     R9, R1                  ; strlen(name) > maximum?
                RBRA    _MNTN_3, N              ; yes
                MOVE    R2, R8
                MOVE    R0, R9
                SYSCALL(strcpy, 1)
                RBRA    _MNTN_4, 1

                ; strlen(name) > maximum: copy maximum + 1 to trigger ellipsis
_MNTN_3         MOVE    R2, R8
                MOVE    R0, R9
                MOVE    R1, R10
                ADD     1, R10
                SYSCALL(memcpy, 1)
                ADD     R10, R9                 ; add zero terminator
                MOVE    0, @R9

                ; set "%s is replaced" flag for filename string to zero
_MNTN_4         MOVE    SCR$OSM_O_DX, R8
                MOVE    @R8, R8
                SUB     1, R8
                ADD     R0, R8
                MOVE    0, @R8

                SYSCALL(leave, 1)
                RET

; ----------------------------------------------------------------------------
; Strings
; ----------------------------------------------------------------------------

FBP_DOT         .ASCII_W "."
STR_MNT_LOAD    .ASCII_W "Inserting the last disk images:\n\n"
LOG_MNT_FILE    .ASCII_W "Remember mounted images: file "
LOG_MNT_ESD     .ASCII_W "Remember mounted images: SD card not mounted\n"
LOG_MNT_ENOF    .ASCII_W "Remember mounted images: file not found (off)\n"
LOG_MNT_ESIZE   .ASCII_W "Remember mounted images: wrong file size (off)\n"
LOG_MNT_EREAD   .ASCII_W "Remember mounted images: read error (off)\n"
LOG_MNT_LOAD    .ASCII_W "Restoring image: "
LOG_MNT_ENOIMG  .ASCII_W "Image not found, skipped\n"
LOG_MNT_ELOAD   .ASCII_W "Image could not be loaded, forgotten\n"
LOG_MNT_SAVED   .ASCII_W "Remember mounted images: saved\n"
LOG_MNT_SDC     .ASCII_W "Remember mounted images: SD card changed (off)\n"
LOG_MNT_EOPEN   .ASCII_W "Remember mounted images: cannot open file (off)\n"
LOG_MNT_EWRITE  .ASCII_W "Remember mounted images: write error (off)\n"
