; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; MegaST: Variables for remembering the mounted disk images (mntmem.asm)
;
; MNT_ENTRIES and MNT_BUF_SIZE (= MNT_ENTRIES * MNT_ENTRY_SZ) come from
; globals.asm, generated by CORE/m2m-rom/make_rom.sh from globals.vhd
;
; done by Chris Freeman in 2026 and licensed under GPL v3
; ****************************************************************************

FB_PATH_MAX     .EQU    255                     ; = MNT_ENTRY_SZ - 1
MNT_ENTRY_SZ    .EQU    256
MNT_FNAME_MAX   .EQU    63
FB_PATH         .BLOCK  256                     ; current dir. of the browser
MNT_PATHS       .BLOCK  MNT_BUF_SIZE            ; one path per entry
MNT_PEND        .BLOCK  MNT_ENTRIES             ; name for the menu pending
MNT_FNAME       .BLOCK  64                      ; MNT_FILE from config.vhd
MNT_FDH         .BLOCK  FAT32$FDH_STRUCT_SIZE   ; file handle
MNT_ON          .BLOCK  1                       ; feature active
MNT_DIRTY       .BLOCK  1                       ; MNT_PATHS changed
MNT_SHOWN       .BLOCK  1                       ; MNT_RESTORE window shown
