## Atari ST/STe for MEGA65 (MegaST)
##
## Core specific constraints
##
## This machine is based on AtariST_MiSTer (https://github.com/MiSTer-devel/AtariST_MiSTer)
## Powered by MiSTer2MEGA65
## MEGA65 port done in 2026 and licensed under GPL v3


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
create_generated_clock -name sdram_clk     [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT1]
create_generated_clock -name ikbd_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT4]

## The three Atari ST clocks are phase aligned (same MMCM): 96.25 MHz = 3 x 32.083 MHz = 48 x 2.005 MHz
## These multicycle paths are the same as in the MiSTer core (AtariST.sdc)

# SDRAM 96 MHz to system 32 MHz
set_multicycle_path -from [get_clocks sdram_clk] -to [get_clocks main_clk] -start -setup 2
set_multicycle_path -from [get_clocks sdram_clk] -to [get_clocks main_clk] -start -hold 1

# System 32 MHz to SDRAM 96 MHz
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks sdram_clk] -end -setup 2
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks sdram_clk] -end -hold 1

# System 32 MHz to 2 MHz
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks ikbd_clk] -start -setup 2
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks ikbd_clk] -start -hold 1

## PMOD headers (serial port, MIDI, parallel port): asynchronous signals, the inputs are
## synchronized by an XPM CDC (see mega65.vhd). Pull-ups keep unconnected inputs inactive.
set_property PULLUP TRUE [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*]}]
set_false_path -to   [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*] pmod1_en_o pmod2_en_o}]
set_false_path -from [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*]}]

## HyperRAM clock: hb_ck_ddr_o_reg (hr_clk) feeds the clock ODDR (hr_clk_del, 90 degrees later), so this path has
## only 2.5 ns. If the placer puts the register 10 or more rows away from the pin (D22, OLOGIC_X0Y205), R4/R5 builds
## missed timing by up to 61 ps (0.4.12). Keep the register next to the pin (a hard pblock: Vivado makes it soft otherwise).
create_pblock pblock_hr_ck
add_cells_to_pblock [get_pblocks pblock_hr_ck] [get_cells {i_framework/i_hyperram/hyperram_ctrl_inst/hb_ck_ddr_o_reg[*]}]
resize_pblock [get_pblocks pblock_hr_ck] -add {SLICE_X0Y200:SLICE_X5Y209}
set_property IS_SOFT FALSE [get_pblocks pblock_hr_ck]
