## Atari ST/STe for MEGA65 (MegaST)
##
## Core specific constraints
##
## This machine is based on AtariST_MiSTer (https://github.com/MiSTer-devel/AtariST_MiSTer)
## Powered by MiSTer2MEGA65
## MEGA65 port done in 2026 and licensed under GPL v3


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
create_generated_clock -name sdram_clk     [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT1]
create_generated_clock -name ikbd_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT4]

## The three Atari ST clocks are phase aligned (same MMCM): 96.25 MHz = 3 x 32.083 MHz = 48 x 2.005 MHz
## These multicycle paths are the same as in the MiSTer core (AtariST.sdc)

# SDRAM 96 MHz to system 32 MHz
set_multicycle_path -from [get_clocks sdram_clk] -to [get_clocks main_clk] -start -setup 2
set_multicycle_path -from [get_clocks sdram_clk] -to [get_clocks main_clk] -start -hold 1

# System 32 MHz to SDRAM 96 MHz
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks sdram_clk] -end -setup 2
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks sdram_clk] -end -hold 1

# System 32 MHz to 2 MHz
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks ikbd_clk] -start -setup 2
set_multicycle_path -from [get_clocks main_clk] -to [get_clocks ikbd_clk] -start -hold 1

## SDRAM (MEGA65 R4/R5/R6)
## All SDRAM signals are registered in the IOBs. The SDRAM clock is the inverted 96 MHz clock
## (ODDR), i.e. the SDRAM samples in the middle of the FPGA's output data eye and the FPGA samples
## the read data one 96 MHz clock cycle later (CAS latency 2), just like on MiSTer.
set_property IOB TRUE [get_ports {sdram_a_o[*] sdram_ba_o[*] sdram_ras_n_o sdram_cas_n_o sdram_we_n_o sdram_cs_n_o sdram_dqml_o sdram_dqmh_o}]
set_property IOB TRUE [get_ports {sdram_dq_io[*]}]
set_false_path -to   [get_ports {sdram_clk_o sdram_cke_o sdram_a_o[*] sdram_ba_o[*] sdram_ras_n_o sdram_cas_n_o sdram_we_n_o sdram_cs_n_o sdram_dqml_o sdram_dqmh_o sdram_dq_io[*]}]
set_false_path -from [get_ports {sdram_dq_io[*]}]

## PMOD headers (serial port, MIDI, parallel port): asynchronous signals, the inputs are
## synchronized by an XPM CDC (see mega65.vhd). Pull-ups keep unconnected inputs inactive.
set_property PULLUP TRUE [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*]}]
set_false_path -to   [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*] pmod1_en_o pmod2_en_o}]
set_false_path -from [get_ports {p1lo_io[*] p1hi_io[*] p2lo_io[*] p2hi_io[*]}]
